### ISSUE TITLE
Specify mechanism for enclave synchronization

### ISSUE THREAD

**Issue by NullHypothesis** [brave/nitriding-daemon#10]
Edit: https://github.com/brave/nitriding-daemon/issues/10#issuecomment-1631067625 puts forward a design for key synchronization and continuity.

Edit: @DJAndries proposes an alternative design that's peer-to-peer in nature:
![image](https://github.com/brave/nitriding-daemon/assets/1316283/f163512f-cbb3-4263-bb80-8e764f6eae88)

**Comment by NullHypothesis** [comment]
> Had a brief conversation about this with our infrastructure folks: Kubernetes supports deployment strategies for replicas. If we want n pods running at the same time, we can ask Kubernetes to start one after another. This should address the problem.

Actually, this would work for the initial rollout but it won't help us with certificate renewals because at that time all enclaves are running.

Two potential solutions:

* Perhaps we could use the [DNS-01](https://letsencrypt.org/docs/challenge-types/#dns-01-challenge) challenge. You prove that you own a domain by putting a challenge into the domain's TXT record. Unfortunately, our Go autocert package doesn't support DNS-01, so it's not straightforward to use.

* As suggested by @DJAndries and [someone else](https://community.letsencrypt.org/t/automating-ssl-certificate-generation-for-multiple-vms-running-behind-azure-load-balancer/139150/4), we could use HTTP-01 and configure the worker enclaves to 301 redirect to the leader enclave. This should work for both the initial certificate setup and subsequent renewals.

**Comment by NullHypothesis** [comment]
## Enabling key re-synchronization

<div align="center">
  <img src="https://github.com/brave/nitriding-daemon/assets/1316283/3779f71d-9b45-448f-80de-38e6fac4f20b" alt="Architecture" width="500">
</div>

1. **Spawning enclaves**. There are two separate Kubernetes deployments:
    1. A _leader_ enclave that's responsible for generating and distributing key material. This enclave is only reachable via k8s's private network.
    2. A set of _worker_ enclaves that are responsible for responding to client requests. These enclaves are reachable over the Internet via an NLB.

   Both deployments must run identical enclave images. This means that we cannot designate the leader at compile time because that would result in the leader and the workers having different image IDs. Instead, we must designate the leader at run time, e.g., by using an HTTP request as a "you are now the leader" signal.

   To allow workers to talk to the leader, the leader must be reachable via a separate domain name, e.g., star-randsrv-leader.bsg.brave.software. We therefore have to extend nitriding so that an enclave is ready to be either the leader or a worker, depending on the aforementioned runtime signal.
2. **HTTPS certificate**. Only the leader responds to Let's Encrypt's HTTP-01 challenge. The leader however is only reachable over k8s's internal network, so worker enclaves proxy Let's Encrypt's challenge request to the leader enclave.
4. **Initial key sync**. Once the leader obtained an HTTPS certificate and generated the randomness server key, it pushes both keys to existing worker enclaves. The leader knows what workers are present by querying the `SRV` record of star-randsrv.bsg.brave.com. Once the key material is pushed, worker enclaves set up their HTTPS server, configure the randomness server, and are now ready to receive client connections. _Note: Instead of doing `SRV`-based worker discovery, workers could register themselves with the leader, e.g., by signaling their presence with an HTTP request. Also, I'm not yet convinced that this push-only model is ideal._
5. **Key re-sync**. The leader must periodically obtain a new HTTPS certificate and rotate its randomness server key. When this happens, the leader pushes the new key material to the worker enclaves. To support the re-issuing of HTTPS certificates, worker enclaves must always be ready to forward HTTP-01 requests to the leader. _Note: This is not great but I cannot think of a simpler alternative._

## Enabling key continuity

The above only supports key synchronization among identical enclaves. If we make changes to star-randsrv, the new enclave images won't be able to sync with existing images. I don't see a way around this without relaxing our threat model because existing enclaves have no way of knowing if they can trust a new enclave.

Perhaps we can work around this by teaching nitriding to be willing to sync with non-identical images if (and only if) the new enclave's HTTPS certificate is recorded in a CT log, or some other type of append-only log. That way, users can verify the evolution of enclave images. Brave could still sneakily introduce a malicious enclave image but _it will get caught_, which serves as a deterrent. There is still a chicken-and-egg problem though: Existing enclaves require new enclaves to have an HTTPS certificate before syncing, and new enclaves won't have a certificate before syncing. There may be a way around this issue; I have to give it some more thought.

**Comment by rillian** [comment]
Seems reasonable. If we use `SRV` records to describe the list of working enclaves, this could also be used to tell new enclaves which role they should assume.

Who initiates the certificate request in this scheme? Does the leader also proxy that through a worker?

Are connections between the leader and the worker over insecure http in this scheme?

**Comment by NullHypothesis** [comment]
> Seems reasonable. If we use `SRV` records to describe the list of working enclaves, this could also be used to tell new enclaves which role they should assume.

For simplicity, shall enclaves assume that they are a worker by default unless told otherwise?

> Who initiates the certificate request in this scheme? Does the leader also proxy that through a worker?

Right, I forgot about that. We could allow outgoing network connections for the leader, which should address this.

> Are connections between the leader and the worker over insecure http in this scheme?

For the Let's Encrypt challenge I would say: yes. It's not confidential.

The subsequent key pushing would however benefit from defense-in-depth. We cannot push the key material over HTTPS because workers don't yet have the certificate but we could have workers _pull_ the key material, which would allow us to use HTTPS. I find a pull model more complex though, and I'm not convinced that the additional complexity justifies the somewhat minor security gains.

**Comment by NullHypothesis** [comment]
> I don't think the security gain is minor. Transferring the private key  for the TLS cert in the clear allows any attacker with network access to MITM subsequent traffic, circumventing the protections against data access AWS claims for their enclave implementation.

Nitriding is [encrypting the key material](https://github.com/brave/nitriding-daemon/blob/master/keysync_responder.go#L106-L115) before sending it as part of the sync protocol. Am I missing something here?

> Something else I'm confused about this is how the leader would be addressed. If it's located based on a separate dns name, how can workers use TLS to authenticate connections to it? Do they alter the validation to accept a cert for the public dns name instead? Do we use e.g. an AWS certificate for the leader? Do we make the leader publicly accessible so it can have a separate letsencrypt certificate?

The design above assumes that the leader has a separate domain name, which could have its own Let's Encrypt certificate.

**Comment by rillian** [comment]
> Nitriding is [encrypting the key material](https://github.com/brave/nitriding-daemon/blob/master/keysync_responder.go#L106-L115) before sending it as part of the sync protocol. Am I missing something here?

No, if we use local encryption between the enclaves authenticated with the ntrio attestation document, that should address the issue.

> The design above assumes that the leader has a separate domain name, which could have its own Let's Encrypt certificate.

Ok, so it's publicly accessible, or we're using the DNS challenge response. Unfortunately, Let's Encrypt doesn't publish a list of IP addresses the http/alpn challenges come from, so we can't firewall the leader either.
