### ISSUE TITLE
Make go install work better

### ISSUE THREAD

**Issue by rillian** [brave/nitriding-daemon#12]
Currently it's possible to build the daemon by invoking the makefile in a checkout:
```sh
git clone https://github.com/brave/nitriding-daemon
go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.52.0
make -C nitriding-daemon/cmd
nitriding-daemon/cmd/nitriding
```

It's also possible to install the daemon directly:
```sh
go install github.com/brave/nitriding-daemon/cmd@v1.0.1
$GOPATH/bin/cmd
```

The second way is shorter, but the daemon ends up named `cmd` which isn't descriptive or unique. It would be better if `go install github.com/brave/nitriding-daemon@latest` resulted in a daemon called `nitriding` directly.

Maybe the source can be re-arranged so cmd is the main module?

**Comment by NullHypothesis** [comment]
Nitriding is currently both a Go package and a standalone executable. I don't think it needs to be a Go package, so we might as well move the stuff in cmd/ to the root directory.
