### ISSUE TITLE
Unable to get attestation report on example

### ISSUE THREAD

**Issue by ma9o** [brave/nitriding-daemon#44]
Hi, I'm unable to get the attestation report from nitriding in the provided example. I've set up gvproxy and forwarded the ports as per the docs:
```bash
curl --unix-socket /tmp/network.sock http:/unix/services/forwarder/expose -X POST -d '{"local":":8443","remote":"192.168.127.2:443"}'
```

I'm running nitriding with these arguments:
```bash
nitriding -fqdn example.com -vsock-ext -extport 443 -intport 8080 -wait-for-app
```

If I understand correctly I should be able to get the attestation report at `https://192.168.127.2:443/enclave/attestation` in the gvproxy-nitriding private network, but when I request `https://localhost:8443/enclave/attestation` the connection is refused:
![image](https://github.com/brave/nitriding-daemon/assets/46647883/ff2bcd3f-fba1-4606-be70-eb80234fd73a)

Also I've specified the nitriding version in the Dockerfile or else the gvproxy connection would error with `cannot read size from socket: EOF` .

gvproxy v0.7.3, nitriding v1.4.2

Thanks!

**Comment by ma9o** [comment]
Solved: Had to remove `-vsock-ext` option.

**Comment by rillian** [comment]
Glad you got it working!
