### ISSUE TITLE
Explain how to set up an enclave-enabled EC2 host

### ISSUE THREAD

**Issue by NullHypothesis** [brave/nitriding-daemon#6]
Let's add a brief section to the README that explains how one can set up an enclave-enabled EC2 host. In particular, let's mention that one has to pick the right instance type, and check the checkbox when creating the EC2 host.

**Comment by jatanloya** [comment]
Hello, is it cool if I make this README?

**Comment by rillian** [comment]
Please do!

**Comment by rillian** [comment]
Resolved by #36. Thanks @jatanloya!
